### ISSUE TITLE
Can I use this with the Rust tracing module?

### ISSUE THREAD

**Issue by happybeing** [BourgondAries/file-rotate#11]
There's an app using the popular Rust `tracing` module which doesn't do `logrotate` style rotation (naming, truncation or compression) and won't work with `tail -f` for example. So I'm looking to add the `logrotate` behaviour and options of `file-rotate` to the app while still using the tracing module.

I'm still fairly new to Rust but have added `file-rotate` to the app and can see it working, so what I need is to modify the code which sets up `tracing` to make it use file-rotate if this is possible. I think this would mean creating a new [tracing_appender::rolling::RollingFileAppender](https://tracing.rs/tracing_appender/rolling/struct.rollingfileappender) which in turn uses `file-rotate` but am not sure.

Can you help or comment? Thanks.

**Comment by Ploppz** [comment]
I don't know much about that library but from a glance it looks like it should indeed not require much work, as you just need to make a struct that implements `MakeWriter`, with `type Writer = FileRotate<_>`, and construct the appropriate `FileRotate` in the `make_writer` function. Because note that `FileRotate` implements `std::io::Write` which is just the trait that is needed here.
With my limited knowledge about how that library works, I could be wrong. I can try to help you further if that didn't help or you run into more trouble.

**Comment by happybeing** [comment]
Thanks very much for the suggestion, is this the idea?
```rust
use file_rotate::{FileRotate, ContentLimit, suffix::CountSuffix, compression::Compression};
    use std::{fs, io::Write};

    use tracing_subscriber::fmt::writer::MakeWriter;
    
    struct MakeTracingWriter {
        writer: FileRotate<CountSuffix>,
    }

    impl<'a> MakeWriter<'a> for MakeTracingWriter {
        type Writer = FileRotate<_>;
    
```

As above rustc complains about the `_` in the last line. If I try `FileRotate<'a>` instead which I think is what is required it also complains because `FileRotate` doesn't support this so I'm not sure if I'm understanding you.

**Comment by happybeing** [comment]
Thanks again for your help. I now have this working and have submitted a PR to add this to the app.

Here's the new code which lets you add `FileRotate` features to a `tracing_appender`:
https://github.com/happybeing/safe_network/blob/node-logrotate/sn/src/bin/sn_node.rs#L74-L144

And here's where it's used:
https://github.com/happybeing/safe_network/blob/node-logrotate/sn/src/bin/sn_node.rs#L180-L184

One extra which would be nice is an implementation of `fmt::Debug` on `FileRotate`. Any chance of that?

**Comment by Ploppz** [comment]
Looks good. So you didn't `impl MakeWriter` in the end? But if it works for your app then that's perfect!

Alright, want me to push a new version with Debug, or let it wait for a future release?

**Comment by happybeing** [comment]
It's a 'nice to have' but in practice is not urgent, just a loose end!

Yeh, not sure why I didn't need to implement `MakeWriter`, maybe I'll find out when something goes wrong!
