### ISSUE TITLE
Add ability to rotate files on creation

### ISSUE THREAD

**Issue by tuxmark5** [BourgondAries/file-rotate#21]
Right now `FileRotate` rotates files only based on content sizes, however I'd like to store each session of my application in a separate file (that way FileRotate would never append to existing to old files and instead would always create a new file to write to). This behavior would mimic `flexi_logger`.

**Comment by Ploppz** [comment]
Does this satisfy your use case? https://github.com/BourgondAries/file-rotate/pull/19

**Comment by tuxmark5** [comment]
Looks good to me. Thanks!

**Comment by Ploppz** [comment]
just released in version 0.7.0-rc.0, btw
