### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by rohitjoshi** [BourgondAries/file-rotate#4]
I don't see any license explicitly mentioned for this crate. Will you be able to publish as Apache 2.0/MIT?

**Comment by BourgondAries** [comment]
@archisgore You ok with re-licensing to MIT? I have LGPL in the Cargo.toml but I changed my mind regarding licensing (a while back in fact), just never got around to it.

**Comment by archisgore** [comment]
Love it! I'm good with it.

**Comment by BourgondAries** [comment]
Thank you, v0.4.0 is now published as MIT.
