### ISSUE TITLE
Old file is truncated when app is restarted

### ISSUE THREAD

**Issue by vbmade2000** [BourgondAries/file-rotate#6]
When the app using fille-rotate is restarted, it should append to old/existing log files. Instead of that it truncates old file and starts writing new logs. IMHO this is not a standard behaviour as old logs are required.

**Comment by Noah-Kennedy** [comment]
Highly relevant, this disqualifies this library from use in most projects that might otherwise use it.

**Comment by Ploppz** [comment]
This has been fixed.

https://github.com/BourgondAries/file-rotate/blob/a6130208f00f4317b58797121691199f2364b635/src/tests.rs#L236
